# Generated by Django 3.0.4 on 2022-05-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=20, unique=True)),
                ('spot_booking', models.BooleanField(null=True)),
                ('spot_class', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotType',
            fields=[
                ('spot_type_name', models.CharField(default='null', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('spot_type_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('user_password', models.CharField(max_length=15)),
                ('user_type', models.BooleanField(null=True)),
                ('user_driving', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='spot_spottype_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_type_name', to='app1.Spot')),
                ('spot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.SpotType')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(default='null', max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.User')),
            ],
        ),
    ]
