# Generated by Django 3.0.4 on 2022-05-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot_spottype_detail',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Spot'),
        ),
    ]
